/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.DataBarang_Controller;
import javax.swing.JComboBox;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Lab Informatika
 */
public class MainView extends javax.swing.JFrame {
    DataBarang_Controller dc;
  
    public MainView() {
        initComponents();
        dc = new DataBarang_Controller(this);
        dc.isiTabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        javax.swing.ButtonGroup buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextNama = new javax.swing.JTextField();
        jComboBoxBarang = new javax.swing.JComboBox<>();
        j3bulan = new javax.swing.JRadioButton();
        j6bulan = new javax.swing.JRadioButton();
        j12bulan = new javax.swing.JRadioButton();
        btnCreate = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableData = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("TOKO CIHUY");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 69, -1, -1));

        jLabel2.setText("Nama Customer");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 148, -1, -1));

        jLabel3.setText("Barang");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 204, -1, -1));

        jLabel4.setText("Cicilan");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 265, -1, -1));
        getContentPane().add(jTextNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 148, 178, -1));

        jComboBoxBarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kulkas", "TV", "Mesin Cuci" }));
        getContentPane().add(jComboBoxBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 204, 178, -1));

        j3bulan.setSelected(true);
        j3bulan.setText("3 Bulan");
        getContentPane().add(j3bulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 265, -1, -1));
        j3bulan.getAccessibleContext().setAccessibleName("");
        j3bulan.getAccessibleContext().setAccessibleDescription("");

        j6bulan.setText("6 Bulan");
        getContentPane().add(j6bulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 304, -1, -1));
        j6bulan.getAccessibleContext().setAccessibleName("");
        j6bulan.getAccessibleContext().setAccessibleDescription("");

        j12bulan.setText("12 Bulan");
        getContentPane().add(j12bulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 343, -1, -1));
        j12bulan.getAccessibleContext().setAccessibleName("");
        j12bulan.getAccessibleContext().setAccessibleDescription("");

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        getContentPane().add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 422, -1, -1));

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 422, -1, -1));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 422, -1, -1));

        TableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nama Customer", "Barang", "Harga Barang", "Cicilan", "Bunga Perbulan", "Angsuran Perbulan", "Total Pembayaran"
            }
        ));
        TableData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableData);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 940, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TableDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableDataMouseClicked
        // TODO add your handling code here:
        dc.selectData();
    }//GEN-LAST:event_TableDataMouseClicked

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        dc.create();
        dc.isiTabel();
        clearField();
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        dc.edit();
        dc.isiTabel();
        clearField();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        dc.delete();
        dc.isiTabel();
        clearField();
    }//GEN-LAST:event_btnDeleteActionPerformed

    public void clearField() {
        jTextNama.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    public JTable getTableData() {
        return TableData;
    }

    public void setTableData(JTable TableData) {
        this.TableData = TableData;
    }

    public JRadioButton getJ12bulan() {
        return j12bulan;
    }

    public void setJ12bulan(JRadioButton j12bulan) {
        this.j12bulan = j12bulan;
    }

    public JRadioButton getJ3bulan() {
        return j3bulan;
    }

    public void setJ3bulan(JRadioButton j3bulan) {
        this.j3bulan = j3bulan;
    }

    public JRadioButton getJ6bulan() {
        return j6bulan;
    }

    public void setJ6bulan(JRadioButton j6bulan) {
        this.j6bulan = j6bulan;
    }

    public JComboBox<String> getjComboBoxBarang() {
        return jComboBoxBarang;
    }

    public void setjComboBoxBarang(JComboBox<String> jComboBoxBarang) {
        this.jComboBoxBarang = jComboBoxBarang;
    }

    public JTextField getjTextNama() {
        return jTextNama;
    }

    public void setjTextNama(JTextField jTextNama) {
        this.jTextNama = jTextNama;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableData;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JRadioButton j12bulan;
    private javax.swing.JRadioButton j3bulan;
    private javax.swing.JRadioButton j6bulan;
    private javax.swing.JComboBox<String> jComboBoxBarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextNama;
    // End of variables declaration//GEN-END:variables
}
